/* ============================================================================
      Execucao:
     isql -i 01_estrutura.sql
   O caminho do banco é absoluto; ajuste a linha CREATE DATABASE se mover a pasta.
   ============================================================================ */

SET SQL DIALECT 3;
SET NAMES UTF8;

CREATE DATABASE 'C:\Projetos\Proj-Ricardo\ControleClientes\banco\CONTROLECLIENTES.FDB'
    USER 'SYSDBA' PASSWORD 'masterkey'
    PAGE_SIZE 8192
    DEFAULT CHARACTER SET UTF8;


-- Tabela ESTADO --

CREATE TABLE ESTADO (
    ID    INTEGER      NOT NULL,
    NOME  VARCHAR(50)  NOT NULL,
    UF    CHAR(2)      NOT NULL,
    CONSTRAINT PK_ESTADO PRIMARY KEY (ID),
    CONSTRAINT UK_ESTADO_UF UNIQUE (UF)
);

-- Tabela CIDADE

CREATE TABLE CIDADE (
    ID        INTEGER      NOT NULL,
    NOME      VARCHAR(50)  NOT NULL,
    ESTADOID  INTEGER      NOT NULL,
    CONSTRAINT PK_CIDADE PRIMARY KEY (ID),
    CONSTRAINT FK_CIDADE_ESTADO FOREIGN KEY (ESTADOID)
        REFERENCES ESTADO (ID) ON UPDATE CASCADE
);

CREATE INDEX IDX_CIDADE_NOME   ON CIDADE (NOME);
CREATE INDEX IDX_CIDADE_ESTADO ON CIDADE (ESTADOID);

-- Tabela CLIENTE

CREATE TABLE CLIENTE (
    ID              INTEGER       NOT NULL,
    NOME            VARCHAR(80)   NOT NULL,
    CEP             CHAR(8),
    CPF_CNPJ        VARCHAR(14),
    ENDERECO        VARCHAR(100),
    NUMERO          VARCHAR(20),
    COMPLEMENTO     VARCHAR(60),
    BAIRRO          VARCHAR(100),
    CIDADE          INTEGER,
    DATANASCIMENTO  DATE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENTE_CIDADE FOREIGN KEY (CIDADE)
        REFERENCES CIDADE (ID) ON UPDATE CASCADE
);

CREATE INDEX IDX_CLIENTE_NOME     ON CLIENTE (NOME);
CREATE INDEX IDX_CLIENTE_CPFCNPJ  ON CLIENTE (CPF_CNPJ);
CREATE INDEX IDX_CLIENTE_CEP      ON CLIENTE (CEP);
CREATE INDEX IDX_CLIENTE_CIDADE   ON CLIENTE (CIDADE);

-- PK automatica

CREATE SEQUENCE GEN_ESTADO_ID;
CREATE SEQUENCE GEN_CIDADE_ID;
CREATE SEQUENCE GEN_CLIENTE_ID;

-- Exception usada pelo trigger de protecao de exclusao

CREATE EXCEPTION EX_CLIENTE_PROTEGIDO
    'Este cliente nao pode ser excluido: o registro esta protegido pela regra do sistema.';

SET TERM ^ ;

CREATE TRIGGER TRG_ESTADO_BI FOR ESTADO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_ESTADO_ID;
END^

CREATE TRIGGER TRG_CIDADE_BI FOR CIDADE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_CIDADE_ID;
END^

CREATE TRIGGER TRG_CLIENTE_BI FOR CLIENTE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = NEXT VALUE FOR GEN_CLIENTE_ID;
END^

CREATE TRIGGER TRG_CLIENTE_BD FOR CLIENTE
ACTIVE BEFORE DELETE POSITION 0
AS
BEGIN
  IF (OLD.ID IN (1, 5, 8, 10, 15)) THEN
    EXCEPTION EX_CLIENTE_PROTEGIDO;
END^

SET TERM ; ^

COMMIT;
